owner: IncantaGames
repo: status

sites:
  - name: Redwood Landing Page
    url: https://redwood.incanta.games
  - name: Incanta Wiki
    url: https://wiki.incanta.games
  - name: Incanta API
    url: https://api.incanta.games
  - name: Incanta API CORS Issues
    url: $CORS_URL

status-website:
  cname: status.incanta.games
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Incanta Status
  introTitle: "**Incanta Games** Status Page"
  introMessage: This is the status page for the various services Incanta Games hosts (including services for Redwood and Unreal plugins).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: night

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
assignees:
  - seesemichaelj