owner: IncantaGames
repo: status

sites:
  - name: Redwood Landing Page
    url: https://redwoodmmo.com
  - name: Incanta Wiki
    url: https://wiki.incanta.games
  - name: Incanta API
    url: https://api.incanta.games
  - name: Incanta API CORS Issues
    url: $CORS_URL

status-website:
  cname: status.incanta.games
  logoUrl: https://user-images.githubusercontent.com/549323/216735372-d1ea8246-b0d0-43a7-b8f0-9229e8c29295.png
  name: Incanta Status
  introTitle: "**Incanta Games** Status Page"
  introMessage: This is the status page for the various services Incanta Games hosts (including services for Redwood and Unreal plugins).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: night

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
assignees:
  - seesemichaelj
